name = "jewelry-sam-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Cloudflare R2 Bucket Binding for Image Storage
[[r2_buckets]]
binding = "SAM_R2_BUCKET"
bucket_name = "jewelry-sam-images"

# Cloudflare KV Binding for Database Storage
[[kv_namespaces]]
binding = "SAM_KV"
id = "6bc9a981a897416fa9e6230c2f647c89"

[vars]
R2_PUBLIC_DOMAIN = "https://jewelry-sam-api.lymin80.workers.dev/r2"
